import { supabase } from './supabase'
import type { TablesInsert } from '../database.types'
import type { UserProfile } from './types'

export type { UserProfile }

export interface CreateProfileData {
  firstName: string
  lastName: string
  birthDate: string
  phoneNumber?: string
  email: string
  isSearchable?: boolean
}

export function calculateAge(birthDateString: string): number {
  const today = new Date()
  const birthDate = new Date(birthDateString)
  let age = today.getFullYear() - birthDate.getFullYear()
  const monthDiff = today.getMonth() - birthDate.getMonth()

  if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birthDate.getDate())) {
    age--
  }

  return age
}

export async function createUserProfile(
  userId: string,
  profileData: CreateProfileData,
): Promise<{ data: UserProfile | null; error: any }> {
  const displayName = `${profileData.firstName.trim()} ${profileData.lastName.trim()}`
  const calculatedAge = calculateAge(profileData.birthDate)

  try {
    // username is generated by a DB trigger; supply a placeholder that will be overwritten
    const insertPayload: TablesInsert<'user_profiles'> = {
      user_id: userId,
      email: profileData.email,
      display_name: displayName,
      first_name: profileData.firstName.trim(),
      last_name: profileData.lastName.trim(),
      birth_date: profileData.birthDate,
      age: calculatedAge,
      phone_number: profileData.phoneNumber?.trim() || null,
      is_searchable: profileData.isSearchable ?? true,
      username: displayName.toLowerCase().replace(/\s+/g, '_'),
    }

    const { data, error } = await supabase
      .from('user_profiles')
      .insert(insertPayload)
      .select()
      .single()

    if (error) {
      console.error('Profile creation error:', error)
      return { data: null, error }
    }

    return { data, error: null }
  } catch (error) {
    console.error('Unexpected error creating profile:', error)
    return { data: null, error }
  }
}

export async function getCurrentUserProfile(): Promise<{
  data: UserProfile | null
  error: any
}> {
  try {
    const {
      data: { user },
      error: userError,
    } = await supabase.auth.getUser()

    if (userError || !user) {
      return { data: null, error: userError || new Error('No user found') }
    }

    const { data, error } = await supabase
      .from('user_profiles')
      .select('*')
      .eq('user_id', user.id)
      .single()

    if (error) {
      console.error('Error fetching profile:', error)
      return { data: null, error }
    }

    return { data, error: null }
  } catch (error) {
    console.error('Unexpected error fetching profile:', error)
    return { data: null, error }
  }
}

export async function getUserProfileById(
  userId: string,
): Promise<{ data: UserProfile | null; error: any }> {
  try {
    const { data, error } = await supabase
      .from('user_profiles')
      .select('*')
      .eq('user_id', userId)
      .single()

    if (error) {
      console.error('Error fetching profile:', error)
      return { data: null, error }
    }

    return { data, error: null }
  } catch (error) {
    console.error('Unexpected error fetching profile:', error)
    return { data: null, error }
  }
}

export async function updateCurrentUserProfile(
  updates: Partial<Omit<UserProfile, 'user_id' | 'id' | 'email' | 'created_at' | 'updated_at'>>,
): Promise<{ data: UserProfile | null; error: any }> {
  try {
    const {
      data: { user },
      error: userError,
    } = await supabase.auth.getUser()

    if (userError || !user) {
      return { data: null, error: userError || new Error('No user found') }
    }

    if (updates.birth_date) {
      updates.age = calculateAge(updates.birth_date)
    }

    const { data, error } = await supabase
      .from('user_profiles')
      .update(updates)
      .eq('user_id', user.id)
      .select()
      .single()

    if (error) {
      console.error('Error updating profile:', error)
      return { data: null, error }
    }

    return { data, error: null }
  } catch (error) {
    console.error('Unexpected error updating profile:', error)
    return { data: null, error }
  }
}

export async function searchUsersByName(
  searchTerm: string,
): Promise<{ data: UserProfile[] | null; error: any }> {
  try {
    const { data, error } = await supabase
      .from('user_profiles')
      .select('*')
      .eq('is_searchable', true)
      .ilike('display_name', `%${searchTerm}%`)
      .order('display_name')

    if (error) {
      console.error('Error searching users:', error)
      return { data: null, error }
    }

    return { data, error: null }
  } catch (error) {
    console.error('Unexpected error searching users:', error)
    return { data: null, error }
  }
}

export async function currentUserHasProfile(): Promise<boolean> {
  try {
    const {
      data: { user },
      error: userError,
    } = await supabase.auth.getUser()

    if (userError || !user) return false

    const { data, error } = await supabase
      .from('user_profiles')
      .select('user_id')
      .eq('user_id', user.id)
      .single()

    return !error && data !== null
  } catch {
    return false
  }
}

export async function deleteCurrentUserProfile(): Promise<{ error: any }> {
  try {
    const {
      data: { user },
      error: userError,
    } = await supabase.auth.getUser()

    if (userError || !user) {
      return { error: userError || new Error('No user found') }
    }

    const { error } = await supabase
      .from('user_profiles')
      .delete()
      .eq('user_id', user.id)

    if (error) {
      console.error('Error deleting profile:', error)
      return { error }
    }

    return { error: null }
  } catch (error) {
    console.error('Unexpected error deleting profile:', error)
    return { error }
  }
}

export async function getSearchableProfiles(
  limit = 50,
): Promise<{ data: UserProfile[] | null; error: any }> {
  try {
    const {
      data: { user },
    } = await supabase.auth.getUser()

    let query = supabase
      .from('user_profiles')
      .select('*')
      .eq('is_searchable', true)
      .limit(limit)
      .order('created_at', { ascending: false })

    if (user) {
      query = query.neq('user_id', user.id)
    }

    const { data, error } = await query

    if (error) {
      console.error('Error fetching searchable profiles:', error)
      return { data: null, error }
    }

    return { data, error: null }
  } catch (error) {
    console.error('Unexpected error fetching searchable profiles:', error)
    return { data: null, error }
  }
}

export async function updateProfileSearchability(
  isSearchable: boolean,
): Promise<{ data: UserProfile | null; error: any }> {
  return updateCurrentUserProfile({ is_searchable: isSearchable })
}

export async function updateProfileAvatar(
  avatarUrl: string,
): Promise<{ data: UserProfile | null; error: any }> {
  return updateCurrentUserProfile({ avatar_url: avatarUrl })
}
